### ISSUE TITLE
no matches for kind "PodDisruptionBudget" in version "policy/v1"

### ISSUE THREAD

**Issue by j143** [j143/microservices-demo#2]
$ kubectl apply -f frontend-pdb.yml
error: unable to recognize "frontend-pdb.yml": no matches for kind "PodDisruptionBudget" in version "policy/v1"

```yml
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: onlineboutique-frontend-pdb
spec:
  minAvailable: 1
```
